{
 "title": "PerfStat",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 31, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "perfstat_minTimeMs", "legendFormat": "__auto" },
    { "expr": "perfstat_avgTimeMs", "legendFormat": "__auto" },
    { "expr": "perfstat_maxTimeMs", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "min",
   "type": "timeseries",
   "gridPos": { "h": 31, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "{__name__=~\"perfstat_minTimeSampleMs\"}",
     "legendFormat": "{{job}} | {{type}} | {{name}} | {{__name__}}"
    }
   ]
  },
  {
   "title": "avg",
   "type": "timeseries",
   "gridPos": { "h": 31, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "{__name__=~\"perfstat_avgTimeSampleMs\"}",
     "legendFormat": "{{job}} | {{type}} | {{name}} | {{__name__}}"
    }
   ]
  },
  {
   "title": "max",
   "type": "timeseries",
   "gridPos": { "h": 31, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "{__name__=~\"perfstat_maxTimeSampleMs\"}",
     "legendFormat": "{{job}} | {{type}} | {{name}} | {{__name__}}"
    }
   ]
  }
 ]
}